QuickFrame.Security/src/QuickFrame.Security/Areas/TransactionLog/Controllers/TrackingController.cs
using ExpressMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using QuickFrame.Security.AccountControl.Models;
using QuickFrame.Security.Data;
using QuickFrame.Security.Data.Dtos;
using QuickFrame.Security.Data.Models;
using System.Collections.Generic;
using System.Linq;
#if NETSTANDARD1_6
using Microsoft.EntityFrameworkCore;
#else
using System.Data.Entity;
#endif

namespace QuickFrame.Security.Areas.TransactionLog.Controllers {

	[Area("TransactionLog")]
	public class TrackingController : Controller {
		private TrackingContext _dbContext;
		private UserManager<SiteUser> _userManager;

		public TrackingController(TrackingContext dbContext, UserManager<SiteUser> userManager) {
			_dbContext = dbContext;
			_userManager = userManager;
		}

		public IActionResult Index() {
			var recordList = new List<AuditLogIndexDto>();
			foreach(var record in _dbContext.AuditLogs)
				recordList.Add(Mapper.Map<AuditLog, AuditLogIndexDto>(record));
			return View(recordList);
		}

		public IActionResult Details(int id) {
			return GetDetailsView("Details", id);
		}

		public IActionResult LogDetails(int id) {
			return GetDetailsView("LogDetails", id);
		}

		private IActionResult GetDetailsView(string viewName, int id) {
			var model = Mapper.Map<AuditLog, AuditLogDetailDto>(_dbContext.AuditLogs.First(log => log.Id == id));
			_dbContext.Entry(model).State = EntityState.Detached;
			var userTask = _userManager.FindByIdAsync(model.UserId);
			userTask.Wait();
			model.UserId = userTask.Result.DisplayName;
			return View(viewName, model);
		}
	}
}

QuickFrame.Security/src/QuickFrame.Security/Areas/TransactionLog/Views/Tracking/Details.cshtml
@model QuickFrame.Security.Data.Dtos.AuditLogDetailDto

@{

	ViewBag.Title = "Audit Logs";
	Layout = "_PopupLayout";
}

<table class="table index table-striped table-bordered table-hover">
	<tr>
		<td>User Id</td>
		<td>@Model.UserId</td>
	</tr>
	<tr>
		<td>Event Date</td>
		<td>@Model.EventDate</td>
	</tr>
	<tr>
		<td>Event Type</td>
		<td>@Model.EventType</td>
	</tr>
	<tr>
		<td>Table Name</td>
		<td>@Model.TableName</td>
	</tr>
	<tr>
		<td>Record Id</td>
		<td>@Model.RecordId</td>
	</tr>
	<tr>
		<td>Original Value</td>
		<td>@Html.Raw(Model.OriginalValue)</td>
	</tr>
	<tr>
		<td>New Value</td>
		<td>@Html.Raw(Model.NewValue)</td>
	</tr>
</table>

QuickFrame.Security/src/QuickFrame.Security/Areas/TransactionLog/Views/Tracking/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<QuickFrame.Security.Data.Dtos.AuditLogIndexDto>

@{

	ViewBag.Title = "Audit Logs";
	ViewBag.UseSearch = true;
	ViewBag.UsePaging = true;
	ViewBag.SearchTerm = Context.Request.Query["searchTerm"];
	Layout = "_Layout";
}

@section menu {
	@Html.Partial("MainMenu")
}

@{
	if(Model.Any()) {
		<table class="table index table-striped table-bordered table-hover" style="border: 0;">
			<thead>
				<tr>
					<th style="width:3%;"></th>
					<th style="width: 25%;">User Id</th>
					<th>Event Date</th>
					<th>Event Type</th>
					<th>Table Name</th>
					<th>Record Id</th>
				</tr>
			</thead>
			<tbody>
				@{
					foreach(var obj in Model) {
						<tr>
							<td style="text-align:center;">
								<div class="dropdown">
									<a href="#" class="dropdown-toggle" style="display:inline-block;width:100%;" data-toggle="dropdown"><i class="fa fa-lg fa-ellipsis-v"></i></a>
									<ul class="dropdown-menu">
										<li><a asp-controller="Tracking" asp-action="Details" asp-route-id="@obj.Id" asp-route-area="TransactionLog" class="fancybox" dta-height="1024px" data-width="1280px" data-scroll="auto"><i class="fa-fw fa fa-info"></i>View Details</a></li>
									</ul>
								</div>
							</td>
							<td>@obj.UserId</td>
							<td>@obj.EventDate</td>
							<td>@obj.EventType</td>
							<td>@obj.TableName</td>
							<td>@obj.RecordId</td>
						</tr>
					}
				}
			</tbody>
		</table>
					}
}

QuickFrame.Security/src/QuickFrame.Security/Areas/TransactionLog/Views/Tracking/LogDetails.cshtml
@model QuickFrame.Security.Data.Dtos.AuditLogDetailDto

@{

	ViewBag.Title = "Audit Logs";
	Layout = "_Layout";
}

<table class="table index table-striped table-bordered table-hover">
	<tr>
		<td>User Id</td>
		<td>@Model.UserId</td>
	</tr>
	<tr>
		<td>Event Date</td>
		<td>@Model.EventDate</td>
	</tr>
	<tr>
		<td>Event Type</td>
		<td>@Model.EventType</td>
	</tr>
	<tr>
		<td>Table Name</td>
		<td>@Model.TableName</td>
	</tr>
	<tr>
		<td>Record Id</td>
		<td>@Model.RecordId</td>
	</tr>
	<tr>
		<td>Original Value</td>
		<td>@Html.Raw(Model.OriginalValue)</td>
	</tr>
	<tr>
		<td>New Value</td>
		<td>@Html.Raw(Model.NewValue)</td>
	</tr>
</table>